version: '3'

services:
  
  php:
    build: ./php
    volumes:
      - ./php/public:/var/www
    restart: always
    depends_on: 
      - postgres
    networks:
      - backend

  nginx:
    image: nginx:1.25.2-alpine
    ports:
      - ${NGINX_PORTS:-80:80}
    volumes:
      - ./php/public:/var/www
      - ./nginx:/etc/nginx/conf.d
    networks:
      - backend
    
  postgres:
    image: postgres:16.0-alpine3.18
    restart: always
    environment:
      - POSTGRES_DB=${DB_NAME:-root}
      - POSTGRES_USER=${DB_USER:-root}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-root}
    ports:
      - ${POSTGRES_PORTS:-5432:5432}
    volumes:
      - ./db_data:/var/lib/postgresql/data
      - ./postgres:/docker-entrypoint-initdb.d/
    networks:
      - backend

  adminer:
    image: adminer:4.8.1-standalone
    restart: always
    depends_on: 
      - postgres
    ports:
      - ${ADMINER_PORTS:-8080:8080}
    networks:
      - backend

networks:
  backend:  
    driver: bridge
volumes:
  db_data:
    driver: local
